name: Run Bet Monitor Bot

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il codice
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa Chrome e dipendenze grafiche Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb libxi6 libgconf-2-4

      - name: Installa le librerie Python
        run: |
          pip install pandas numpy beautifulsoup4 selenium webdriver-manager requests undetected-chromedriver

      - name: Esegui lo Script sotto schermo virtuale
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        # xvfb-run simula la presenza di un monitor a cui Chrome può agganciarsi
        run: xvfb-run --server-args="-screen 0 1920x1080x24" python AS_best_low.py
